version: 2

jobs:
  build:
    docker:
      - image: circleci/node:17

    working_directory: ~/repo

    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-

      - run: yarn

      - save_cache:
          paths:
            - node_modules
            - yarn.lock
          key: v1-dependencies-{{ checksum "package.json" }}

      - run: yarn test
      - run: yarn lint
      - run: yarn type-check
